### ISSUE TITLE
Misleading error message if missing creds_set_dried in dp_init

### ISSUE THREAD

**Issue by leslem** [amashadihossein/dpbuild#68]
I accidentally left out creds_set_dried when running dp_init with an s3 board. This is the error message I got:

```
Error in dp_init(project_path = "~/devel/dp-penguins/", project_description = "Exploratory data product from penguins",  : 
  board_params_set_dried which is expected for s3_board
```

The error message is coming from here:
https://github.com/amashadihossein/dpbuild/blob/main/R/dp_init.R#L106

It's checking to see if creds_set_dried is missing, but only mentions board_params_set_dried, and doesn't mention that it's missing.

It would be better to say something along the lines of: "Missing creds_set_dried, which is required for s3_board"

**Comment by geauxdojang** [comment]
Thanks @leslem 

Since this is checking if creds_set_dried parameter is missing or not, changing board_params_set_dried in the output string to similar lines you mentioned sounds good. dp_init method is general one that can be applied for both s3 and labkey. 

We also have a [ticket](https://github.com/users/amashadihossein/projects/2?pane=issue&itemId=16653783) around safeguarding creds_set_dried parameter where I added this issue about having correct message when params are missing. Thanks.

```r
if (missing(creds_set_dried)) {
      stop(cli::format_error(glue::glue(
        "board_params_set_dried which is ",
        "expected for {board_type}"
      )))
    }
```

**Comment by geauxdojang** [comment]
@leslem @amashadihossein I corrected the error message in dp_init and made a [pull request](https://github.com/amashadihossein/dpbuild/pull/69/commits/33afef6de5b2841b67000196f7664ac6245eb0c4). Thanks.
